name: Add Secrets to Key Vault

on:
  workflow_call:
    inputs:
      runner-name:
        required: true
        type: string
      parameters-file: # parameters-file is used in the 'Extract Resource Group Name' and 'Extract Key Vault Name' steps (to extract the name and environment)
        required: true
        type: string
      secretName:
        required: true
        type: string
      secretValue:
        required: true
        type: string
        
permissions:
  id-token: write
  contents: read

jobs:
  deploy-resources:
    runs-on: ${{ inputs.runner-name }}

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: 'Extract Resource Group Name'
        id: get-rg
        run: |
          NAME=$(jq -r '.parameters.name.value' ${{ inputs.parameters-file }})
          ENV=$(jq -r '.parameters.environment.value' ${{ inputs.parameters-file }})
          RG_NAME=rg-${NAME}-${ENV}
          echo "rg_name=$RG_NAME" >> $GITHUB_OUTPUT ### rg_name is used in the 'Add Secrets to Key Vault' step
          echo "Resource Group Name: $RG_NAME"

      - name: 'Extract Key Vault Name'
        id: get-kv
        run: |
          NAME=$(jq -r '.parameters.name.value' ${{ inputs.parameters-file }})
          ENV=$(jq -r '.parameters.environment.value' ${{ inputs.parameters-file }})
          KV_NAME=kv-${NAME}-${ENV}
          echo "kv_name=$KV_NAME" >> $GITHUB_OUTPUT ### kv_name is used in the 'Add Secrets to Key Vault' step
          echo "Key Vault Name: $KV_NAME"
      
      - name: 'Add Secrets to Key Vault'
        run: |
          az deployment group create \
          --resource-group ${{ steps.get-rg.outputs.rg_name }} \ ### rg_name variable defined in the 'Extract Resource Group Name' step
          --template-file ./bicep/add_secrets_to_keyvault.bicep \
          --parameters SecretName=${{ inputs.secretName }} \
          --parameters SecretValue=${{ inputs.secretValue }} \
          --parameters keyVaultName=${{ steps.get-kv.outputs.kv_name }} ### kv_name variable defined in the 'Extract Key Vault Name' step