name: Deploy Azure Resources

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main    # Triggers DEV deployment
      - staging # Triggers TST deployment
      - release # Triggers PRD deployment

permissions:
  id-token: write
  contents: read

jobs:
  # DEV
  call-reusable-workflow-dev:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy_resources_reusable.yaml
    with:
      runner-name: "owned-runner-DEV" # Runner that is owned by the organization and has access to the Virtual Network
      parameters-file: infra/params/dev_params.json
  
  # TST
  call-reusable-workflow-tst:
    if: github.ref == 'refs/heads/staging' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy_resources_reusable.yaml
    with:
      runner-name: "owned-runner-TST"
      parameters-file: infra/params/tst_params.json 

  # PRD
  call-reusable-workflow-prd:
    if: github.ref == 'refs/heads/release' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy_resources_reusable.yaml
    with:
      runner-name: "owned-runner-PRD"
      parameters-file: infra/params/prd_params.json
