name: Deploy Azure Resources

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # DEV
  call-reusable-workflow-dev:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/add_keyvault_secrets_reusable.yaml
    with:
      runner-name: "owned-runner-DEV" # Runner that is owned by the organization and has access to the Virtual Network
      parameters-file: infra/params/dev_params.json
      secretName: "POSTGRES_PASSWORD" # Name of the secret to add to the Key Vault (must be the same as the secret name in the repository secrets)
    secrets:
      secretValue: ${{ secrets.POSTGRES_PASSWORD }} # Secret value that is stored in the repository secrets

  # TST
  call-reusable-workflow-tst:
    if: github.ref == 'refs/heads/staging' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/add_keyvault_secrets_reusable.yaml
    with:
      runner-name: "owned-runner-TST"
      parameters-file: infra/params/tst_params.json
      secretName: "POSTGRES_PASSWORD"
    secrets:
      secretValue: ${{ secrets.POSTGRES_PASSWORD }}

  # PRD
  call-reusable-workflow-prd:
    if: github.ref == 'refs/heads/release' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/add_keyvault_secrets_reusable.yaml
    with:
      runner-name: "owned-runner-PRD"
      parameters-file: infra/params/prd_params.json
      secretName: "POSTGRES_PASSWORD"
    secrets:
      secretValue: ${{ secrets.POSTGRES_PASSWORD }}
